name: backbone_regen
channels:
  - bioconda
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alembic=1.16.4
  - aniso8601=9.0.1
  - annotated-types=0.6.0
  - appdirs=1.4.4
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - bcrypt=4.3.0
  - biopython=1.78
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cachetools=5.5.1
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.1.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cryptography=44.0.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=12.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - databricks-sdk=0.63.0
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - docker-py=7.1.0
  - docker-pycreds=0.4.0
  - eval_type_backport=0.2.2
  - executing=0.8.3
  - expat=2.7.1
  - fastapi=0.112.2
  - filelock=3.17.0
  - flask=3.1.0
  - fmt=11.1.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2025.5.1
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glib=2.84.2
  - glib-tools=2.84.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.38.0
  - graphene=3.3
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - grpcio=1.71.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gunicorn=23.0.0
  - h11=0.16.0
  - h5py=3.14.0
  - hdf5=1.14.5
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.1.0
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=14.0.6
  - llvmlite=0.44.0
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.2.3
  - mamba=2.1.0
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mlflow=3.2.0
  - mlflow-skinny=3.2.0
  - mlflow-ui=3.2.0
  - more-itertools=10.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.1.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nglview=3.1.2
  - nlohmann_json=3.11.3
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.4
  - opentelemetry-api=1.30.0
  - opentelemetry-sdk=1.30.0
  - opentelemetry-semantic-conventions=0.51b0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - paramiko=3.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.1
  - prometheus_flask_exporter=0.22.4
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py3dmol=2.5.3
  - pyarrow=19.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pynacl=1.5.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pypdb=2.4
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pytorch_geometric=2.6.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - querystring_parser=1.2.4
  - re2=2024.07.02
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rsa=4.7.2
  - s2n=1.5.14
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - sentry-sdk=2.18.0
  - setproctitle=1.3.6
  - setuptools=78.1.1
  - simdjson=3.12.3
  - sip=6.7.12
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - spdlog=1.15.3
  - sqlalchemy=2.0.41
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - stack_data=0.2.0
  - starlette=0.38.2
  - sympy=1.13.3
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - torchmetrics=1.4.0.post0
  - torchtriton=2.3.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvicorn=0.35.0
  - wandb=0.21.0
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - docutils==0.17.1
      - e3nn==0.5.6
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - griddataformats==1.0.2
      - isoduration==20.11.0
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - mda-xdrlib==0.2.0
      - mdanalysis==2.9.0
      - mistune==3.1.3
      - mmcif-pdbx==2.0.1
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.1.1
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pdb2pqr==3.7.1
      - prometheus-client==0.22.1
      - propka==3.5.1
      - python-json-logger==3.3.0
      - referencing==0.36.2
      - rpds-py==0.26.0
      - scipy==1.16.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.7
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - types-python-dateutil==2.9.0.20250708
      - uri-template==1.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
prefix: /home/v_sidorov/.conda/envs/backbone_regen
